# Generated by Django 2.1.5 on 2020-12-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('str_date', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=20)),
                ('heading', models.CharField(max_length=100)),
                ('page_text', models.TextField()),
                ('text', models.TextField()),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('title_low', models.CharField(max_length=150)),
            ],
        ),
    ]
